/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bp2;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nurettin YILDIZ
 */
public class Calısanlar_Ekranı extends javax.swing.JFrame {

    /**
     * Creates new form Calısanlar_Ekranı
     */
    DefaultTableModel tbl_table_model;
    public Calısanlar_Ekranı() {
        initComponents();
        tbl_table_model = new DefaultTableModel();
        tbl_table_model.setColumnIdentifiers(new Object[]{"personId", "nameSurname", "Email","Gender","Position"});
        tbl_staff.setModel(tbl_table_model);
        txt_search.setBackground(new java.awt.Color(0,0,0,1));
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_employee3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_staff = new javax.swing.JTable();
        lbl_search = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        lbl__title = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        separator = new javax.swing.JSeparator();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Staff Mangement");

        pnl_employee3.setBackground(new java.awt.Color(0, 0, 0));
        pnl_employee3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl_staff.setBackground(new java.awt.Color(255, 255, 255));
        tbl_staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PersoneId", "NameSurname", "Email", "Gender", "Position"
            }
        ));
        tbl_staff.setSelectionBackground(new java.awt.Color(0, 102, 204));
        jScrollPane4.setViewportView(tbl_staff);

        lbl_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_search.setForeground(new java.awt.Color(0, 255, 255));
        lbl_search.setText("Search By person Id,name surname, email");

        btn_search.setBackground(new java.awt.Color(0, 255, 255));
        btn_search.setForeground(new java.awt.Color(0, 0, 0));
        btn_search.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nurettin YILDIZ\\Documents\\NetBeansProjects\\bp2Project2\\src\\main\\java\\Images\\search x30.png")); // NOI18N
        btn_search.setText("SEARCH");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        lbl__title.setBackground(new java.awt.Color(0, 0, 0));
        lbl__title.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl__title.setForeground(new java.awt.Color(0, 255, 255));
        lbl__title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl__title.setText("Staff Management");

        txt_search.setBackground(new java.awt.Color(0, 0, 0));
        txt_search.setForeground(new java.awt.Color(0, 255, 255));
        txt_search.setBorder(null);
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(0, 0, 0));
        btn_exit.setForeground(new java.awt.Color(0, 255, 255));
        btn_exit.setText("X");
        btn_exit.setBorder(null);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_employee3Layout = new javax.swing.GroupLayout(pnl_employee3);
        pnl_employee3.setLayout(pnl_employee3Layout);
        pnl_employee3Layout.setHorizontalGroup(
            pnl_employee3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_employee3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnl_employee3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_employee3Layout.createSequentialGroup()
                        .addComponent(lbl_search, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_employee3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(separator)
                            .addComponent(txt_search, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                .addGap(106, 106, 106))
            .addGroup(pnl_employee3Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(lbl__title, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_employee3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_employee3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        pnl_employee3Layout.setVerticalGroup(
            pnl_employee3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_employee3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_exit)
                .addGap(14, 14, 14)
                .addComponent(lbl__title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(pnl_employee3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_search, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_employee3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_employee3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // burada company_db den aldığım method ve manuel aldığım string değer sayesinde tablotu search edip kayıtlı personelleri görüntülüyorum.For döngüsü ve ArrayList yardımı ile.
         String search  = txt_search.getText();
        ArrayList <Personel> plist  = Company_db.SearchByNameEmailOrPersonId(search);
        tbl_table_model.setRowCount(0);
        for (Personel np1 : plist) {
            tbl_table_model.addRow(new Object[] {np1.personId, np1.name_surname, np1.email,np1.gender,np1.position });
            
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calısanlar_Ekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calısanlar_Ekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calısanlar_Ekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calısanlar_Ekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calısanlar_Ekranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_search;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl__title;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JPanel pnl_employee3;
    private javax.swing.JSeparator separator;
    private javax.swing.JTable tbl_staff;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
