/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bp2;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nurettin YILDIZ
 */
public class Giriş_Ekranı extends javax.swing.JFrame {

    /**
     * Creates new form Giriş_Ekranı
     */
    public static String loginEmail;

    public Giriş_Ekranı() {
        initComponents();
        txt_email.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtp_password.setBackground(new java.awt.Color(0, 0, 0, 1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();
        kGradientPanel1 = new bp2.KGradientPanel();
        lbl_epos = new javax.swing.JLabel();
        lbl_photo = new javax.swing.JLabel();
        pnl_right = new javax.swing.JPanel();
        txt_email = new javax.swing.JTextField();
        txtp_password = new javax.swing.JPasswordField();
        sprt_username = new javax.swing.JSeparator();
        sprt_password = new javax.swing.JSeparator();
        lbl_password = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        btn_Sign_up = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        lbl_photo_user = new javax.swing.JLabel();
        lbl_photo_password = new javax.swing.JLabel();
        lbl_welcome = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setMinimumSize(new java.awt.Dimension(600, 600));

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 204));

        lbl_epos.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbl_epos.setText("       Ebizmarts || E-POS");

        lbl_photo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nurettin YILDIZ\\Documents\\NetBeansProjects\\bp2Project2\\src\\main\\java\\Images\\Fotoram.io.png")); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbl_epos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lbl_photo)
                .addGap(20, 20, 20))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_epos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pnl_right.setBackground(new java.awt.Color(255, 255, 255));
        pnl_right.setForeground(new java.awt.Color(255, 255, 255));

        txt_email.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(0, 0, 0));
        txt_email.setText("admin@gmail.com");
        txt_email.setBorder(null);

        txtp_password.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtp_password.setForeground(new java.awt.Color(0, 0, 0));
        txtp_password.setText("Password");
        txtp_password.setBorder(null);
        txtp_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtp_passwordActionPerformed(evt);
            }
        });

        sprt_username.setBackground(new java.awt.Color(0, 0, 0));
        sprt_username.setForeground(new java.awt.Color(255, 255, 255));

        sprt_password.setBackground(new java.awt.Color(255, 255, 255));
        sprt_password.setForeground(new java.awt.Color(255, 255, 255));

        lbl_password.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(0, 0, 0));
        lbl_password.setText("Password");

        lbl_email.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 0, 0));
        lbl_email.setText("Email");

        btn_Sign_up.setBackground(new java.awt.Color(34, 222, 204));
        btn_Sign_up.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btn_Sign_up.setForeground(new java.awt.Color(0, 0, 0));
        btn_Sign_up.setText("Sign Up");
        btn_Sign_up.setBorder(null);
        btn_Sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Sign_upActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(34, 222, 204));
        btn_login.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btn_login.setForeground(new java.awt.Color(0, 0, 0));
        btn_login.setText("Login");
        btn_login.setBorder(null);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        lbl_photo_user.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nurettin YILDIZ\\Documents\\NetBeansProjects\\bp2Project2\\src\\main\\java\\Images\\icons8-user-25.png")); // NOI18N

        lbl_photo_password.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nurettin YILDIZ\\Documents\\NetBeansProjects\\bp2Project2\\src\\main\\java\\Images\\icons8-password-25.png")); // NOI18N

        lbl_welcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_welcome.setText("    Welcome to login");

        javax.swing.GroupLayout pnl_rightLayout = new javax.swing.GroupLayout(pnl_right);
        pnl_right.setLayout(pnl_rightLayout);
        pnl_rightLayout.setHorizontalGroup(
            pnl_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_rightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(pnl_rightLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(pnl_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_photo_user, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_photo_password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnl_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sprt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_rightLayout.createSequentialGroup()
                        .addComponent(btn_Sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtp_password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_password)
                    .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sprt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        pnl_rightLayout.setVerticalGroup(
            pnl_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_rightLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lbl_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_photo_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(sprt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtp_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_photo_password, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(sprt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(281, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtp_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtp_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtp_passwordActionPerformed

    private void btn_Sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Sign_upActionPerformed
        // TODO add your handling code here:
        Kayıt_Ekranı k1 = new Kayıt_Ekranı();
        k1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Sign_upActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // Aldığım email ve password değerlerinin databasede olup olmadığını kontrol ediyorum ona göre giriş sağlıyorum
        
        String email = txt_email.getText().trim();
        String password = txtp_password.getText().trim();

        if (!email.isEmpty() && !password.isEmpty()) {
            if (Company_db.Login(email, password) != null) {
                loginEmail = email;
                Ana_Menu ana_Menu = new Ana_Menu();
                ana_Menu.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "The login process is not successful");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Email or password is empty");
        }

    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giriş_Ekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giriş_Ekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giriş_Ekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giriş_Ekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giriş_Ekranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sign_up;
    private javax.swing.JButton btn_login;
    private java.awt.Canvas canvas1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private bp2.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_epos;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JLabel lbl_photo_password;
    private javax.swing.JLabel lbl_photo_user;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPanel pnl_right;
    private javax.swing.JSeparator sprt_password;
    private javax.swing.JSeparator sprt_username;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txtp_password;
    // End of variables declaration//GEN-END:variables
}
